Documentation/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Documentation.Service.Core;
using Documentation.Service.Models;


namespace Documentation.Controllers
{
    public class CategoryController : Controller
    {

        private readonly CategoryService _categoryService;

        public CategoryController(CategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {

            var models = _categoryService.GetAll();
            return View(models);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpGet("/Category/Update/{id}")]
        public IActionResult Update(int id)
        {
            Category category = _categoryService.GetById(id);
            return View(category);
        }
        public IActionResult UpdateAction(Category model)
        {
            _categoryService.Update(model);
            TempData["success"] = "Kategori Başarılı Bir Şekilde Güncellendi";
            return RedirectToAction("Index");

        }
        public IActionResult Save(Category model)
        {
            _categoryService.Save(model);

            TempData["success"] = "Kategori Başarılı Bir Şekilde Kaydedildi";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _categoryService.Delete(id);
            TempData["success"] = "Kategori Başarılı Bir Şekilde Silindi";
            return RedirectToAction("Index");
        }
    }
}

Documentation/Controllers/DokumanController.cs
using Microsoft.AspNetCore.Mvc;
using Documentation.Service.Core;
using Documentation.Service.Models;


namespace Documentation.Controllers
{
    public class DokumanController : Controller
    {

        private readonly DokumanService _DokumanService;
        private readonly CategoryService _categoryService;




        public DokumanController(DokumanService DokumanService, CategoryService categoryService)
        {
            _DokumanService = DokumanService;
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {

            var models = _DokumanService.GetAll();

            return View(models);
        }

        public IActionResult Create()
        {
            ViewBag.CategoryList = _categoryService.GetAll();
            return View();
        }
        [HttpGet("/Dokuman/Update/{id}")]
        public IActionResult Update(int id)
        {
            ViewBag.CategoryList = _categoryService.GetAll();
            Dokuman dokuman = _DokumanService.GetById(id);
            return View(dokuman);
        }
        public IActionResult UpdateAction(Dokuman model)
        {

            _DokumanService.Update(model);
            TempData["success"] = "Doküman Başarılı Bir Şekilde Güncellendi";
            return RedirectToAction("Index");
        }
        public IActionResult SaveAction(Dokuman model)
        {

            _DokumanService.Save(model);

            TempData["success"] = "Doküman Başarılı Bir Şekilde Kaydedildi";
            return RedirectToAction("Index");
        }
        public IActionResult DeleteAction(int id)
        {
            _DokumanService.Delete(id);
            TempData["success"] = "Doküman Başarılı Bir Şekilde Silindi";
            return RedirectToAction("Index");
        }
    }
}

Documentation/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Documentation.Service.Core;
using Documentation.Service.Models;


namespace Documentation.Controllers
{
    public class RoleController : Controller
    {

        private readonly RoleService _roleService;

        public RoleController(RoleService roleService)
        {
            _roleService = roleService;
        }
        public IActionResult Index()
        {

            var models = _roleService.GetAll();
            return View(models);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpGet("/Role/Update/{id}")]
        public IActionResult Update(int id)
        {
            Role role = _roleService.GetById(id);
            return View(role);
        }
        public IActionResult UpdateAction(Role model)
        {
            _roleService.Update(model);
            TempData["success"] = "Rol Başarılı Bir Şekilde Güncellendi";
            return RedirectToAction("Index");

        }
        public IActionResult Save(Role model)
        {
            _roleService.Save(model);

            TempData["success"] = "Rol Başarılı Bir Şekilde Kaydedildi";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _roleService.Delete(id);
            TempData["success"] = "Rol Başarılı Bir Şekilde Silindi";
            return RedirectToAction("Index");
        }
    }
}

Documentation/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Documentation.Service.Core;
using Documentation.Service.Models;

namespace Documentation.Controllers
{
    public class UserController : Controller
    {

        private readonly UserService _UserService;
        private readonly RoleService _roleService;




        public UserController(UserService UserService, RoleService roleService)
        {
            _UserService = UserService;
            _roleService = roleService;
        }
        public IActionResult Index()
        {

            var models = _UserService.GetAll();

            return View(models);
        }

        public IActionResult Create()
        {
            ViewBag.RoleList = _roleService.GetAll();
            return View();
        }
        [HttpGet("/User/Update/{id}")]
        public IActionResult Update(int id)
        {
            ViewBag.RoleList = _roleService.GetAll();
            User user = _UserService.GetById(id);
            return View(user);
        }
        public IActionResult UpdateAction(User model)
        {
            if (model.Password != null && !model.Password.Equals(""))
            {
                model.Password = UserService.HashPassword(model.Password);
            }
            else
            {
                model.Password = _UserService.GetById(model.UserID).Password;
            }
            _UserService.Update(model);
            TempData["success"] = "Kullanıcı Başarılı Bir Şekilde Güncellendi";
            return RedirectToAction("Index");
        }
        public IActionResult SaveAction(User model)
        {
            if (model.Password != null && !model.Password.Equals(""))
            {
                model.Password = UserService.HashPassword(model.Password);
            }
            else
            {
                model.Password = _UserService.GetById(model.UserID).Password;
            }
            _UserService.Save(model);
            TempData["success"] = "Kullanıcı Başarılı Bir Şekilde Kaydedildi";
            return RedirectToAction("Index");
        }
        public IActionResult DeleteAction(int id)
        {
            _UserService.Delete(id);
            TempData["success"] = "Kullanıcı Başarılı Bir Şekilde Silindi";
            return RedirectToAction("Index");
        }


    }
}

Documentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Maware</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container p-5 my-5 bg-dark text-white">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Maware</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index">Kategoriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Dokuman" asp-action="Index">Dokumantasyonlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Role" asp-action="Index">Roller</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Giriş</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Maware Coredb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Documentation/Views/Shared/_TestLayout.cshtml
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />

<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-blue-gray w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menu</h3>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 25px;">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy" style="font-size: 25px;">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index" style="font-size: 25px;">Kategoriler</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Haber" asp-action="Index" style="font-size: 25px;">Haberler</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index" style="font-size: 25px;">Giriş</a>
        </li>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>
            ForXHaber
            </h1>
        </div>


        <div class="w3-container">
            @RenderBody();
        </div>

    </div>

</body>
</html>